# Generated by Django 5.0.6 on 2024-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_remove_order_total_remove_order_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='to_gram',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
        migrations.AddField(
            model_name='stock',
            name='to_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='to_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
